# Generated by Django 3.0.8 on 2020-07-27 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('progress', models.CharField(choices=[('WI', 'Wishlist'), ('AP', 'Applied'), ('PH', 'Phone'), ('OS', 'Onsite'), ('OF', 'Offer'), ('RE', 'Rejected')], default='WI', max_length=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
