# Generated by Django 3.1.1 on 2020-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('AP', 'Applied'), ('PH', 'Phone'), ('OS', 'Onsite'), ('OF', 'Offer')], default='WI', max_length=8),
        ),
    ]
