# Generated by Django 3.1.1 on 2020-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200907_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, help_text='Don\'t forget to put "http://" at the beginning.', null=True),
        ),
    ]
