# Generated by Django 3.1.3 on 2020-11-29 12:39

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0004_auto_20201129_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True, null=True, verbose_name='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.job')),
            ],
        ),
    ]
