# Generated by Django 3.1.3 on 2020-11-13 13:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name=''),
        ),
    ]
