# Generated by Django 3.1.3 on 2020-11-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201112_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
