# Generated by Django 3.1.1 on 2020-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Phone', 'Phone'), ('Onsite', 'Onsite'), ('Offer', 'Offer')], default='AP', max_length=8),
        ),
    ]
