# Generated by Django 3.1.1 on 2020-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201015_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Phone', 'Phone'), ('Onsite', 'Onsite'), ('Offer', 'Offer')], default='Applied', max_length=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, help_text='Don\'t forget to put "https://" at the beginning.', null=True),
        ),
    ]
