# Generated by Django 3.1.1 on 2020-11-10 12:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201102_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notes',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
