# Generated by Django 3.1.3 on 2020-11-29 12:39

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201102_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='', max_length=8),
        ),
    ]
