# Generated by Django 3.1.4 on 2020-12-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20201207_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(choices=[('applied', 'Applied'), ('phone', 'Phone'), ('onsite', 'Onsite'), ('offer', 'Offer')], max_length=8),
        ),
    ]
