# Generated by Django 3.1.3 on 2020-11-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20201110_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
    ]
