# Generated by Django 3.1.3 on 2020-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='', max_length=8),
        ),
    ]
