# Generated by Django 3.2 on 2021-05-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20210318_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='progress',
            new_name='status',
        ),
    ]
